### PR TITLE
[WIP] Json formatted logging for ocsgw

### PR DESCRIPTION
**Pull request by vihangpatil**

### CODE REVIEW

**Comment by vihangpatil** [comment]
@mpeterss I have changed both files - `logback.xml` and `logback.dev.xml` to do json formatted logging.  But we need normal logging for acceptance tests.  I'm not sure which file is used for AT and which one is used in `dev`/`prod` env.

**Comment by vihangpatil** [comment]
@mpeterss The solution can be verified by `docker-compose up --build` in `ocsgw`.

**Review by mpeterss — CHANGES_REQUESTED** [review]
We will hold off with this until we get feedback from Google how this is supposed to work. For now I have set the nodes to use the cloud logger.

**Comment by mpeterss** [comment]
This is broken in GCP
Please star the ticket
https://issuetracker.google.com/137517429

**Comment by vihangpatil** [comment]
This will not work due to the limitation in GCP. Closing the PR.

**Pull request closed without merging**
