### PR TITLE
Feature/publisher updates

### PR DESCRIPTION
**Pull request by prasanthu**

### CODE REVIEW

**Review by mpeterss — APPROVED** [review]
LGTM

**Review by kmmatwork — APPROVED** [review]
LGTM

**Review by vihangpatil — COMMENTED** [review]
Will need one more PR to consolidate multiple implementations.

**Comment by prasanthu** [comment]
> Will need one more PR to consolidate multiple implementations.

I am working on it [https://github.com/ostelco/ostelco-core/pull/922]

**Pull request merged**
